// LCM type definitions
// This file automatically generated by lcm-gen.
// DO NOT MODIFY BY HAND!!!!

import 'dart:convert';
import 'dart:typed_data';
import 'package:lcm_dart/lcm_dart.dart';

class ExampleT implements LcmMessage {
  static const int LCM_FINGERPRINT = 0x1baa9e29b0fbaa8b;

  int timestamp;
  List<double> position;
  List<double> orientation;
  int num_ranges;
  List<int> ranges;
  String name;
  bool enabled;

  ExampleT({
    required this.timestamp,
    required this.position,
    required this.orientation,
    required this.num_ranges,
    required this.ranges,
    required this.name,
    required this.enabled,
  });

  @override
  int get lcmFingerprint => LCM_FINGERPRINT;

  @override
  void encode(LcmBuffer buf) {
    buf.putInt64(LCM_FINGERPRINT);
    buf.putInt64(timestamp);
    for (var i0 = 0; i0 < 3; i0++) {
      buf.putFloat64(position[i0]);
    }
    for (var i0 = 0; i0 < 4; i0++) {
      buf.putFloat64(orientation[i0]);
    }
    buf.putInt32(num_ranges);
    for (var i0 = 0; i0 < num_ranges; i0++) {
      buf.putInt16(ranges[i0]);
    }
    {
      final bytes = utf8.encode(name);
      buf.putUint32(bytes.length + 1);
      buf.putUint8List(bytes);
      buf.putUint8(0);
    }
    buf.putUint8(enabled ? 1 : 0);
  }

  static ExampleT decode(LcmBuffer buf) {
    final fingerprint = buf.getInt64();
    if (fingerprint != LCM_FINGERPRINT) {
      throw Exception('Invalid fingerprint');
    }

    final timestamp = buf.getInt64();
    final position = List.generate(3, (_) => buf.getFloat64());
    final orientation = List.generate(4, (_) => buf.getFloat64());
    final num_ranges = buf.getInt32();
    final ranges = List.generate(num_ranges, (_) => buf.getInt16());
    final name = () {
      final len = buf.getUint32();
      final bytes = buf.getUint8List(len - 1);
      buf.getUint8(); // null terminator
      return utf8.decode(bytes);
    }();
    final enabled = buf.getUint8() != 0;

    return ExampleT(
      timestamp: timestamp,
      position: position,
      orientation: orientation,
      num_ranges: num_ranges,
      ranges: ranges,
      name: name,
      enabled: enabled,
    );
  }
}
